# Site Settings

disqus:              #"your-disqus"

paginate:            10

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:                [jekyll-paginate]

sass:
  sass_dir: assets/css
  style: :nested
