title:  "MSR Portfolio"
tagline: "Robot Projects"
description:
author:
  name: "Elton Cheng"

menu:
- {name: 'About Myself', file: 'about.html'}
- {name: 'Projects', file: 'All.html'}
- {name: 'Robotics', file: 'facts.html'}
- {name: 'Controls & Simulations', file: 'sample-posts.html'}
- {name: 'Other', file: 'Other.html'}
- {name: 'Resume', file: 'Resume.pdf'}

social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/elton-cheng/'}
- {icon: 'envelope', link: 'mailto:elton.c22@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer

